### ISSUE TITLE
Unittests failing because pattoo_agent.yaml file is absent

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/pattoo-web#145]
I've changed pattoo-web to have its configuration parameters for communication to the pattoo api to be moved from pattoo_agent.yaml to pattoo_webd.yaml like this.

```
pattoo_webd:
  ip_listen_address: 127.0.0.1
  ip_bind_port: 20200
pattoo_web_api:
  ip_address: 127.0.0.1
  ip_bind_port: 20202

```
We may not need the creation of pattoo_agent.yaml for the unittests to pass. Please verify and adjust.

`FileNotFoundError: [Errno 2] No such file or directory: '/home/peter/.pattoo-web-unittests/config/pattoo_agent.yaml'`
